[build-system]
requires = ["setuptools>=68.0", "wheel", "build"]
build-backend = "setuptools.build_meta"

[project]
name = "xuri-rpc-websocket"
version = "1.1.0"
description = "WebSocket sender for xuri-rpc"
license = {text = "MIT"}
authors = [
    {name = "prometheus0017"},
]
keywords = ["rpc", "remote", "callback", "websocket"]
requires-python = ">=3.9"
dependencies = [
    "xuri-rpc>=1.0.0",
    "websockets>=12.0",
    "cbor2>=5.4",
]

[tool.setuptools.packages.find]
include = ["xuri_rpc_websocket*"]
